services:
  db:
    image: postgres
    restart: always
    user: postgres
    ports: 
      - "5432:5432"
    volumes:
      - db-data:/var/lib/db-data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=testdb

volumes:
  db-data: {}